### ISSUE TITLE
Add documentation for remaining detectors and vulnerabilities

### ISSUE THREAD

**Issue by arturoBeccar** [CoinFabrik/scout#108]
## Description
Add documentation for remaining detectors and vulnerabilities

## Acceptance Criteria
For each new type of detector and vulnerability, complete:
- Detector documentation: Add new readme (named: <NUMBER>-<VULNERABILITY_NAME>) with Detector Documentation to [this folder](https://github.com/CoinFabrik/scout/tree/main/docs/docs/detectors).
- Vulnerability Class summary: Add new numbered section [at the bottom of the Vulnerability Classes](https://github.com/CoinFabrik/scout/blob/main/docs/docs/vulnerabilities/README.md#vulnerability-classes) documentation.
- Vulerability Class documentation: Add new readme (named: <NUMBER>-<VULNERABILITY_NAME>) with a detailed Vulnerability Class documentation to [this folder](https://github.com/CoinFabrik/scout/tree/main/docs/docs/vulnerabilities).
- Detector table: Add new row to [Detectors table](https://github.com/CoinFabrik/scout#detectors) in main README.md

Also, remember to update the number of identified vulnerabilities at the [beginning of the Vulnerability Classes](https://github.com/CoinFabrik/scout/blob/main/docs/docs/vulnerabilities/README.md#vulnerability-classes)

## Subtasks
- [ ] Documentation for delegate-call
- [ ] Documentation for zero-address-check
- [ ] Documentation for insufficiently-random-values
- [ ] Documentation for unrestricted-transfer-from

## Estimate
1

## Sprint number
1
