### ISSUE TITLE
Review and correct detector documentation

### ISSUE THREAD

**Issue by arturoBeccar** [CoinFabrik/scout#172]
## Description
Review and correct detector documentation.

## Tasks
- [ ] Read detector documentation.
- [ ] Correct grammar and missing documentation.
- [ ] Update README.md in main.

## Known problems
- Missing hyphen `-` on detector names.
- Missing lazy-delegate on README.md in main.
- Only `reentrancy` detector. Should have 2 detectors reentrancy-1 and reentrancy-2.

## Estimate
1
